run:
  dir: .
job:
  chdir: false
output_subdir: null
job_logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: "[%(asctime)s] %(message)s"
      datefmt: "%H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers: [console]
hydra_logging:
  version: 1
  disable_existing_loggers: true
  root:
    handlers: []